# Valid credentials
VALID_USERNAME = "Admin"
VALID_PASSWORD = "admin123"

# Invalid credentials
INVALID_USERNAME = "Admin"
INVALID_PASSWORD = "wrongpassword"

# Employee data
EMPLOYEE_FIRST_NAME = "John"
EMPLOYEE_LAST_NAME = "TestAuto"


SEARCH_EMPLOYEE_NAME = "John"
SEARCH_EMPLOYEE_ID = "1037"
INVALID_EMPLOYEE_NAME = "XYZNOTEXIST123"

SEARCH_EMPLOYEE_ID = "0001"